package com.kenny.common.mybatis.pager;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseMapper<T extends Serializable, PK extends Serializable, Example> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	long countByExample(Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	int deleteByExample(Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	int deleteByPrimaryKey(PK id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	int insert(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	int insertSelective(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	List<T> selectByExample(Example example);

	/**
	 * 这个要加,会改变rowBounds的offset和limit的值，用来做分页。RowBounds本来是逻辑分页的，我们自己写拦截器将其转化为物理分页
	 * selectList(String statement) selectList(String statement, Object
	 * parameter) selectList(String statement, Object parameter, RowBounds
	 * rowBounds)
	 * 
	 * @param example
	 * @param rowBounds
	 * @return
	 */
	List<T> selectByExample(Example example, RowBounds rowBounds);

	// 不能加Page对象，底层的org.mybatis.spring.SqlSessionTemplate.class#selectList，这个函数有多个重载但是不支持Page等第三方对象
	// List<T> selectByExample(Example example, RowBounds rowBounds, Page page);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	T selectByPrimaryKey(PK id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	int updateByExampleSelective(@Param("record") T record, @Param("example") Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	int updateByExample(@Param("record") T record, @Param("example") Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	int updateByPrimaryKeySelective(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tb_student_info
	 *
	 * @mbggenerated Tue Jan 31 17:08:05 CST 2017
	 */
	int updateByPrimaryKey(T record);
}